[project]
name = "mlops-capstone-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohammed Ameeen", email = "ameencrcr70@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "joblib>=1.6.0",
    "mlflow>=2.22.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
]

[project.scripts]
mlops-capstone-project = "mlops_capstone_project:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
